/** Isolated native package management + browser design regression; no model tokens or real installs. */
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import WebSocket from 'ws';
import { chromium } from 'playwright-core';
import { CHROME_PATH } from './lib/chrome.mjs';
import { portUp } from './lib/port-utils.mjs';
const port=9210,token='extensions-fixture',clientId='extensions-fixture';
assert.equal(await portUp(port),false,'Port busy');
const root=mkdtempSync(join(tmpdir(),'extensions-e2e-')),cwd=join(root,'work'),agent=join(root,'agent'),pkg=join(root,'local-tools');
for(const dir of [cwd,agent,pkg,join(pkg,'extensions'),join(agent,'extensions')])mkdirSync(dir);
writeFileSync(join(pkg,'package.json'),JSON.stringify({name:'local-tools',version:'1.2.0',description:'Local package fixture for native Pi settings.',pi:{extensions:['extensions/main.js'],skills:[],prompts:[],themes:[]}}));
writeFileSync(join(pkg,'extensions/main.js'),'export default () => {};');
mkdirSync(join(agent,'skills/design-fixture'),{recursive:true});writeFileSync(join(agent,'skills/design-fixture/SKILL.md'),'---\nname: design-fixture\ndescription: Settings v2 native skill fixture\n---\nUse native behavior.');
writeFileSync(join(agent,'extensions/footer.js'),'export default () => {};');
writeFileSync(join(agent,'settings.json'),JSON.stringify({packages:[pkg],defaultProvider:'fixture',defaultModel:'fixture'}));
writeFileSync(join(agent,'models.json'),JSON.stringify({providers:{fixture:{api:'openai-completions',baseUrl:'http://127.0.0.1:1',apiKey:'fixture',models:[{id:'fixture',name:'Fixture',input:['text'],contextWindow:32000,maxTokens:4000,cost:{input:0,output:0,cacheRead:0,cacheWrite:0}}]}}}));
writeFileSync(join(agent,'webui-extensions.json'),JSON.stringify({autoCheck:false}));
writeFileSync(join(agent,'auth.json'),JSON.stringify({fixture:{type:'api_key',key:'local'}}));
const serverExecutable=process.argv.includes('--electron-node')?(await import('electron')).default:process.execPath;
const server=spawn(serverExecutable,['dist/server/index.js'],{env:{...process.env,...(process.argv.includes('--electron-node')?{ELECTRON_RUN_AS_NODE:'1'}:{}),PORT:String(port),PI_WEB_TOKEN:token,PI_WEB_CWD:cwd,PI_CODING_AGENT_DIR:agent,PI_WEB_DATA_DIR:join(root,'data')},stdio:['ignore','pipe','pipe']});
let logs='',ws,browser;server.stdout.on('data',d=>logs+=d);server.stderr.on('data',d=>logs+=d);
const req=async(action,args={},headers={})=>{const res=await fetch(`http://127.0.0.1:${port}/api/extensions`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...headers},body:JSON.stringify({clientId,cwd,action,...args})});const text=await res.text();let body;try{body=JSON.parse(text);}catch{body={error:text};}return{status:res.status,...body};};
const wait=async(fn)=>{for(let i=0;i<200;i++){const v=await fn();if(v)return v;await new Promise(r=>setTimeout(r,50));}throw Error('timeout '+logs.slice(-2000));};
const mutation=async(state,operation)=>{const job=await req('start',{version:state.version,operation});assert.equal(job.status,200,JSON.stringify(job));const done=await wait(async()=>{const result=await req('job',{id:job.id});return result.phase!=='running'&&result;});assert.equal(done.phase,'done',JSON.stringify(done));return req('list');};
try{
 await wait(()=>portUp(port));ws=new WebSocket(`ws://127.0.0.1:${port}/ws?token=${token}`);const messages=[];ws.on('message',d=>messages.push(JSON.parse(d)));await new Promise((r,j)=>{ws.on('open',r);ws.on('error',j);});ws.send(JSON.stringify({type:'hello',clientId}));await wait(()=>messages.some(m=>m.type==='snapshot'));
 assert.equal((await req('list',{}, {Origin:'https://evil.invalid'})).status,403);
 assert.equal((await req('list',{cwd:root})).status,409);
 assert.equal((await req('open-info',{id:'skills:user'})).absolute,join(agent,'skills'));
 assert.equal((await req('skills-list',{}, {Origin:'https://evil.invalid'})).status,403);
 assert.equal((await req('skills-list',{cwd:root})).status,409);
 let state=await req('list');assert.equal(state.status,200,JSON.stringify(state));const item=state.packages.find(p=>p.name==='local-tools');assert(item);assert(state.packages.some(p=>p.kind==='file'));
 state=await mutation(state,{action:'toggle',id:item.id,enabled:false});assert.equal(state.packages.find(p=>p.id===item.id).enabled,false);
 state=await mutation(state,{action:'toggle',id:item.id,enabled:true});assert.equal(state.packages.find(p=>p.id===item.id).enabled,true);
 const another=join(root,'another-package');mkdirSync(another);writeFileSync(join(another,'package.json'),JSON.stringify({name:'another-package',version:'1.0.0',pi:{extensions:[]}}));
 const details=await req('details',{source:another});assert.equal(details.name,'another-package');assert.equal(details.ticket,undefined);
 assert.equal((await req('details',{source:another},{Origin:'https://evil.invalid'})).status,403);
 assert.equal((await req('details',{source:another,cwd:root})).status,409);
 const preview=await req('preview',{source:another});assert.equal(preview.name,'another-package');
 state=await mutation(state,{action:'install',scope:'user',ticket:preview.ticket});assert(state.packages.some(p=>p.name==='another-package'));
 state=await mutation(state,{action:'remove',id:state.packages.find(p=>p.name==='another-package').id});assert(existsSync(join(another,'package.json')));

 const file=state.packages.find(p=>p.kind==='file');const opened=await req('file',{id:file.id});assert.equal(opened.status,200);
 assert.equal((await req('save-file',{id:file.id,version:'stale',content:'no'})).status,400);
 const edited='export default () => {}; // editor fixture';assert.equal((await req('save-file',{id:file.id,version:opened.version,content:edited})).status,200);assert.equal(readFileSync(file.path,'utf8'),edited);
 assert.equal((await req('file',{id:item.id})).status,400);
 assert.equal((await req('preferences',{enabled:false})).autoCheck,false);
 if(process.argv.includes('--browser')){
  browser=await chromium.launch({executablePath:CHROME_PATH||chromium.executablePath()});const page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(20000);const errors=[];page.on('response',async res=>{if(res.url().includes('/api/extensions')&&res.status()>=400)console.error('API',await res.text());});page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(id=>{sessionStorage.setItem('pi-web-client-id',id);localStorage.setItem('pi-extensions-autocheck','false');},clientId);
  await page.goto(`http://127.0.0.1:${port}/?token=${token}`);await page.getByRole('button',{name:'设置',exact:true}).first().click();await page.getByText('所有设置',{exact:true}).click();await page.getByRole('button',{name:'Extensions',exact:true}).click();
  const panel=page.locator('.extensions-panel');await panel.getByText('local-tools',{exact:true}).waitFor();
  await panel.getByRole('button',{name:'查看详情 local-tools',exact:true}).click();await panel.getByRole('button',{name:'移除引用',exact:true}).waitFor();
  await page.screenshot({path:'tests/scratch/extensions-installed.png',fullPage:true});
  await panel.getByRole('switch',{name:'启用 local-tools',exact:true}).click();await wait(async()=>Array.isArray(JSON.parse(readFileSync(join(agent,'settings.json'),'utf8')).packages[0].extensions)&&!JSON.parse(readFileSync(join(agent,'settings.json'),'utf8')).packages[0].extensions.length);
  await panel.getByText('操作完成',{exact:true}).waitFor();await wait(async()=>!await panel.getByRole('switch',{name:'启用 local-tools',exact:true}).isChecked());await panel.getByRole('switch',{name:'启用 local-tools',exact:true}).click();await wait(async()=>await panel.getByRole('switch',{name:'启用 local-tools',exact:true}).isChecked());
  await panel.getByRole('button',{name:'从 npm / git 安装',exact:true}).click();await panel.locator('.ext-dialog input').fill(another);await panel.getByRole('button',{name:'查看安装信息',exact:true}).click();await panel.locator('.ext-security').waitFor();await page.screenshot({path:'tests/scratch/extensions-install.png',fullPage:true});
  const dialog=panel.locator('.ext-dialog');await dialog.getByRole('button',{name:'关闭',exact:true}).focus();await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'安装');
  let failedOnce=false;const failInstall=async route=>{const body=route.request().postDataJSON();if(body.action==='start'&&body.operation?.action==='install'&&!failedOnce){failedOnce=true;return route.fulfill({json:{id:'failed-fixture',phase:'error',error:'Fixture install failure',log:'Step one\nFixture install failure'}});}return route.continue();};
  await page.route('**/api/extensions**',failInstall);await dialog.getByRole('button',{name:'安装',exact:true}).click();await dialog.getByRole('alert').filter({hasText:'Fixture install failure'}).waitFor();assert(await dialog.isVisible());
  await dialog.getByRole('button',{name:'重试',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.unroute('**/api/extensions**',failInstall);
  await panel.getByRole('tab',{name:'已安装 · 2',exact:true}).waitFor();await panel.locator('.ext-new').waitFor();assert((await req('list')).packages.some(p=>p.name==='another-package'&&p.scope==='user'));
  await panel.getByRole('button',{name:'查看详情 footer.js',exact:true}).click();await panel.getByRole('button',{name:'编辑文件',exact:true}).click();await panel.getByRole('textbox',{name:'编辑文件',exact:true}).fill('export default () => {}; // browser editor');await panel.getByRole('button',{name:'保存文件',exact:true}).click();await panel.locator('.ext-editor').waitFor({state:'hidden'});assert(readFileSync(file.path,'utf8').includes('browser editor'));
  await page.route('**/api/extensions**',async route=>{const body=route.request().postDataJSON();if(body.action==='details')return route.fulfill({json:{source:body.source,name:'fixture-catalog',description:'Native extension catalog fixture.',license:'MIT',repository:'https://example.com/source',resources:{extensions:['main.ts'],skills:['skills/one','skills/two']},canPin:true}});
  if(body.action!=='search')return route.continue();return route.fulfill({json:{page:1,pages:1,items:[{name:'fixture-catalog',description:'Native extension catalog fixture.',version:'1.2.3',author:'Pi community',downloads:12500,date:Date.now(),types:['extension','skill'],url:'https://pi.dev/packages/fixture-catalog'}]}});});
  await panel.getByRole('tab',{name:/浏览 pi.dev/}).click();await panel.getByText('fixture-catalog',{exact:true}).waitFor();await panel.getByRole('button',{name:'查看详情 fixture-catalog',exact:true}).click();await panel.getByText('MIT',{exact:true}).waitFor();assert.equal(await panel.locator('.ext-catalog-detail .ext-resource-counts').innerText(),'扩展 1\n技能 2');
  await page.screenshot({path:'tests/scratch/extensions-browse.png',fullPage:true});
  await page.evaluate(()=>document.documentElement.setAttribute('data-appearance','dark'));await page.screenshot({path:'tests/scratch/extensions-browse-dark.png',fullPage:true});
  await page.evaluate(()=>document.documentElement.setAttribute('data-appearance','light'));
  await page.setViewportSize({width:390,height:844});assert(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1));await page.screenshot({path:'tests/scratch/extensions-browse-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1050});
  await panel.getByRole('tab',{name:/已安装/}).click();
  await page.getByRole('button',{name:'技能',exact:true}).click();
  const skills=page.locator('.settings-skills');await skills.getByRole('switch',{name:'启用 design-fixture',exact:true}).waitFor();
  await skills.getByRole('searchbox',{name:'搜索技能名称或描述'}).fill('design-fixture');
  await skills.getByRole('switch',{name:'启用 design-fixture',exact:true}).click();
  await wait(async()=>JSON.parse(readFileSync(join(agent,'settings.json'),'utf8')).skills?.some(p=>p.startsWith('-')&&p.includes('design-fixture')));
  await skills.getByRole('button',{name:'重载当前会话',exact:true}).click();
  await page.screenshot({path:'tests/scratch/settings-v2-skills.png',fullPage:true});
  await page.getByRole('button',{name:'更新',exact:true}).click();await panel.getByText('local-tools',{exact:true}).waitFor();
  assert(!await panel.getByText('pi-harness',{exact:true}).count());assert(!await panel.getByText('footer.js',{exact:true}).count());
  await panel.getByRole('switch').waitFor();assert(!await panel.getByRole('switch').isChecked());
  await panel.getByRole('switch').check();await wait(()=>JSON.parse(readFileSync(join(agent,'webui-extensions.json'),'utf8')).autoCheck===true);
  await panel.getByRole('switch').uncheck();await wait(()=>JSON.parse(readFileSync(join(agent,'webui-extensions.json'),'utf8')).autoCheck===false);
  await page.screenshot({path:'tests/scratch/settings-v2-updates.png',fullPage:true});
  await page.getByRole('button',{name:'MCP 与 Codemode',exact:true}).click();
  const mcp=page.locator('.mcp-workbench');await mcp.getByRole('button',{name:'编辑 mcp.json',exact:true}).click();
  const json=mcp.locator('.mcp-json-dialog');await json.locator('textarea').fill('{"mcpServers":{},"autoEnableCodemode":false}');
  await json.getByRole('button',{name:'保存',exact:true}).click();await wait(()=>JSON.parse(readFileSync(join(agent,'mcp.json'),'utf8')).autoEnableCodemode===false);
  await wait(async()=>await json.getByRole('button',{name:'保存',exact:true}).isDisabled());await json.getByRole('button',{name:'关闭',exact:true}).click();
  assert.equal(await mcp.locator('textarea').count(),0);await page.screenshot({path:'tests/scratch/settings-v2-mcp.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});assert(await mcp.evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await page.getByRole('button',{name:'技能',exact:true}).click();await skills.getByRole('switch',{name:'启用 design-fixture',exact:true}).waitFor();assert(await skills.evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await page.getByRole('button',{name:'Extensions',exact:true}).click();await panel.getByText('local-tools',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'tests/scratch/extensions-mobile.png',fullPage:true});assert(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await page.setViewportSize({width:1440,height:1050});await page.evaluate(()=>localStorage.setItem('pi-harness:lang','en'));await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).first().click();await page.getByText('All settings',{exact:true}).click();await page.getByRole('button',{name:'Extensions',exact:true}).click();await page.locator('.ext-header').getByRole('button',{name:'Install from npm / git',exact:true}).waitFor();await page.locator('.extensions-panel').getByText('local-tools',{exact:true}).waitFor();await page.screenshot({path:'tests/scratch/extensions-en.png',fullPage:true});
  assert.deepEqual(errors,[]);await browser.close();browser=undefined;
 }
 console.log('PASS native packages: auth/origin/cwd, list, toggle, preview, install, local remove, browser desktop/mobile');
}catch(e){console.error(logs.slice(-4000));throw e;}finally{await browser?.close();ws?.terminate();server.kill();if(server.exitCode===null)await new Promise(r=>server.once('exit',r));rmSync(root,{recursive:true,force:true});}
