// Real workspace + SDK + local provider, isolated from the user's files/configuration.
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright-core';
import { CHROME_PATH } from './lib/chrome.mjs';
import { portUp } from './lib/port-utils.mjs';
const port = 8994;
for (const p of [port, port + 1]) assert.equal(await portUp(p), false, `Port ${p} busy`);
const base = mkdtempSync(join(tmpdir(), 'pi-wiki-ui-'));
const cwd = join(base, 'wiki'), agent = join(base, 'agent');
mkdirSync(join(cwd, '交易系统'), { recursive: true }); mkdirSync(join(cwd, 'risk')); mkdirSync(agent);
writeFileSync(join(cwd, 'README.md'), '---\ntags: [风控, 交易]\n---\n# 风控规则\n\n本文定义下单前和持仓中的风控检查，参数见 [[参数配置]]。\n\n## 单笔止损\n\n单笔亏损达到账户净值的 2% 时强制平仓，不等待信号确认。\n\n## 仓位上限\n\n单品种不超过净值的 20%，总敞口不超过 60%。\n');
writeFileSync(join(cwd, '交易系统', '参数配置.md'), '# 参数配置\n\n#风控\n\n止损阈值 0.02，参考 [[README]]。\n');
writeFileSync(join(cwd, 'risk', 'guard.py'), 'def check_stop(loss):\n    return loss >= 0.02\n');
mkdirSync(join(cwd, '.obsidian'));
writeFileSync(join(cwd, '.obsidian', 'hidden.md'), '---\ntitle: Different page title\n---\n# Different body title\n\nHidden searchable document.');
writeFileSync(join(cwd, 'large.md'), Buffer.alloc(2 * 1024 * 1024 + 1, 'x'));
writeFileSync(join(cwd, 'README.md'), readFileSync(join(cwd, 'README.md'), 'utf8').replace('tags: [风控, 交易]', 'title: 风控规则\ntags: [风控, 交易, Alpha, Beta, Gamma, Delta, Omega, Theta]') + '\n```js\nconst color = "#ff475040"; // #notatag\n```\n\n#abc #abcd #abcdef #abcdef12 `#inline`\n');
const requests = [];
const mock = createServer(async (req, res) => {
	let body = ''; for await (const chunk of req) body += chunk;
	const payload = JSON.parse(body); requests.push(payload);
	res.writeHead(200, { 'content-type': 'text/event-stream' });
	const afterTools = payload.messages.at(-1)?.role === 'tool';
	const writeCalls = [
		{ path: 'README.md', content: readFileSync(join(cwd, 'README.md'), 'utf8') + '\n## 隔夜持仓\n\n隔夜持仓的止损阈值按开盘价重新计算。\n' },
		{ path: '交易系统/参数配置.md', content: '# 参数配置\n\n#风控\n\n新增 overnight_reset: true\n' },
	];
	const confirmation = JSON.stringify(payload.messages.filter(m => m.role === 'user')).includes('仅确认当前文档');
	const chunks = confirmation ? [[{ role: 'assistant', content: '当前文档已确认。' }, null], [{}, 'stop']] : afterTools ? [[{ role: 'assistant', reasoning_content: '先核对文档范围和已完成的修改。' }, null], [{ content: '已更新两个文档。跳过 guard.py：本次未授权修改代码。' }, null], [{ content: '\n\n- **第 2 节补充建议**：可以明确仓位上限的例外。\n- **第 99 节不存在**：不应出现跳转。\n\n需要我继续吗？' }, null], [{}, 'stop']] : [[{ role: 'assistant', tool_calls: writeCalls.map((args, index) => ({ index, id: `wiki-write-${index}`, type: 'function', function: { name: 'write', arguments: JSON.stringify(args) } })) }, null], [{}, 'tool_calls']];
	if (!afterTools) await new Promise(r => setTimeout(r, 1200));
	for (const [delta, finish_reason] of chunks) {
		if (afterTools) await new Promise(r => setTimeout(r, 800));
		res.write(`data: ${JSON.stringify({ id: 'wiki-test', object: 'chat.completion.chunk', created: Date.now(), model: payload.model, choices: [{ index: 0, delta, finish_reason }] })}\n\n`);
	}
	res.end('data: [DONE]\n\n');
});
await new Promise(r => mock.listen(port + 1, '127.0.0.1', r));
writeFileSync(join(agent, 'models.json'), JSON.stringify({ providers: { wiki: { api: 'openai-completions', baseUrl: `http://127.0.0.1:${port + 1}`, apiKey: 'local-test', models: [{ id: 'wiki-test', name: 'Wiki test', input: ['text'], contextWindow: 32000, maxTokens: 4096 }] } } }));
writeFileSync(join(agent, 'settings.json'), JSON.stringify({ defaultProvider: 'wiki', defaultModel: 'wiki-test', defaultTools: ['+codemode', '+tool_search'] }));
writeFileSync(join(agent, 'auth.json'), JSON.stringify({ wiki: { type: 'api_key', key: 'local-test' } }));
const server = spawn(process.execPath, ['dist/server/index.js'], { env: { ...process.env, PORT: String(port), PI_WEB_CWD: cwd, PI_WEB_DATA_DIR: join(base, 'data'), PI_CODING_AGENT_DIR: agent }, stdio: ['ignore', 'pipe', 'pipe'] });
let log = ''; server.stdout.on('data', d => log += d); server.stderr.on('data', d => log += d);
let browser;
try {
	for (let i = 0; i < 100 && !await portUp(port); i++) await new Promise(r => setTimeout(r, 100));
	browser = await chromium.launch({ executablePath: CHROME_PATH || chromium.executablePath() });
	const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
	page.setDefaultTimeout(10000);
	let holdSnapshots = false, releaseSnapshots;
	await page.routeWebSocket('**/ws', ws => {
		const upstream = ws.connectToServer(), pending = [];
		releaseSnapshots = () => { holdSnapshots = false; for (const message of pending.splice(0)) ws.send(message); };
		upstream.onMessage(message => {
			const type = JSON.parse(String(message)).type;
			if (holdSnapshots && ['snapshot', 'snapshot_delta', 'conversations'].includes(type)) pending.push(message);
			else ws.send(message);
		});
	});
	let activeConversation, activeSnapshot; const wikiConversations = [];
	page.on('websocket', ws => ws.on('framereceived', ({ payload }) => { try { const msg = JSON.parse(String(payload)); if (msg.type === 'snapshot') { activeConversation = msg.state.conversationId; activeSnapshot = msg.state; } } catch {} }));
	page.on('response', async response => { if (response.url().endsWith('/api/wiki') && response.request().postDataJSON()?.action === 'new-conversation' && response.ok()) wikiConversations.push((await response.json()).conversationId); });
	const errors = []; page.on('pageerror', e => { errors.push(e.message); console.error('Browser error:', e.message); });
	await page.addInitScript(cwd => { localStorage.setItem(`pi-wiki-file:${cwd}`, '交易系统/参数配置.md'); localStorage.setItem('pi-web-ui:appearance', 'dark'); localStorage.setItem(`pi-wiki-chat:${cwd}`, 'false'); }, cwd);
	await page.goto(`http://127.0.0.1:${port}`);
	await page.locator('.conn-dot.ok').first().waitFor({ state: 'attached', timeout: 20000 });
	assert.equal(await page.getByRole('tab', { name: 'Wiki 模式', exact: true }).count(), 0);
	await page.locator('.file-name', { hasText: 'README.md' }).click();
	await page.locator('.wiki-document h1:visible', { hasText: '风控规则' }).waitFor();
	assert.equal(await page.locator('.wiki-workbench').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(36, 35, 41)');
	assert.equal(await page.locator('.wiki-sidebar').evaluate(el => Math.round(el.getBoundingClientRect().width)), 250);
	await page.locator('.wiki-chat-panel').waitFor();
	assert.equal(Math.round((await page.locator('.wiki-chat-panel').boundingBox()).width), 400);
	assert((await page.locator('.wiki-chat-model').innerText()).includes('Wiki test'));
	assert.equal(await page.locator('.wiki-main > .wiki-composer-area').count(), 0, 'panel open hides floating input');
	const reading = await page.locator('.wiki-main').boundingBox(), panel = await page.locator('.wiki-chat-panel').boundingBox();
	assert(reading.x + reading.width <= panel.x, 'desktop panel does not cover article');
	await page.locator('.wiki-chat-panel').getByRole('button', { name: '收起对话面板', exact: true }).click();
	await page.keyboard.press('Meta+j');
	await page.locator('.wiki-chat-panel').waitFor();
	await page.keyboard.press('Meta+j');
	await page.locator('.wiki-index-status').waitFor();
	assert.equal(await page.locator('.wiki-document h1:visible').count(), 1);
	assert.equal(await page.locator('.wiki-limit').count(), 0);
	assert.equal(await page.locator('.wiki-tags, .wiki-all-tags').count(), 0);
	assert.equal(await page.locator('.wiki-document-meta button', { hasText: '#' }).count(), 0);
	assert.equal(await page.getByRole('treeitem', { name: '.obsidian', exact: true }).count(), 0);
	await page.getByRole('treeitem', { name: '隐藏文件夹 · 1', exact: true }).click();
	await page.getByRole('treeitem', { name: '.obsidian', exact: true }).waitFor();
	assert.equal(await page.evaluate(cwd => localStorage.getItem(`pi-wiki-hidden:${cwd}`), cwd), 'true');
	await page.getByRole('treeitem', { name: '隐藏文件夹 · 1', exact: true }).click();
	await page.locator('.wiki-index-status').click();
	await page.getByRole('dialog').getByText('large.md', { exact: true }).waitFor();
	await page.getByRole('dialog').getByText('单个文件超过 2 MB', { exact: true }).waitFor();
	await page.keyboard.press('Escape');
	assert(await page.getByRole('button', { name: '展开提问框', exact: true }).isVisible());
	assert(!(await page.getByRole('textbox', { name: '问 pi', exact: true }).isVisible()));
	await page.keyboard.press('/');
	await page.getByRole('textbox', { name: '问 pi', exact: true }).fill('retain this draft');
	await page.keyboard.press('Escape');
	await page.getByRole('button', { name: '展开提问框', exact: true }).click();
	assert.equal(await page.getByRole('textbox', { name: '问 pi', exact: true }).inputValue(), 'retain this draft');
	await page.getByRole('textbox', { name: '问 pi', exact: true }).fill('');
	await page.keyboard.press('Escape');
	assert.equal(await page.locator('.wiki-toc button').count(), 2);
	await page.locator('.wiki-toc button').last().click();
	await page.waitForFunction(() => document.querySelector('.wiki-toc button:last-child')?.getAttribute('aria-current') === 'location');
	assert((await page.locator('.wiki-document-meta').innerText()).includes('分钟读完'));
	const readingCode = await page.locator('.wiki-prose .codeblock').evaluate(el => getComputedStyle(el).backgroundColor);
	await page.evaluate(() => { localStorage.setItem('pi-web-ui:code-theme', 'dark'); window.dispatchEvent(new Event('pi-web-ui:code-theme')); });
	assert.equal(readingCode, "rgb(30, 28, 24)");
	assert.equal(await page.locator(".wiki-prose .codeblock").evaluate(el => getComputedStyle(el).backgroundColor), readingCode);
	assert.equal(await page.locator('.wiki-prose select[data-code-language]').first().inputValue(), 'js');
	await page.locator('.wiki-scroll').evaluate(el => { el.scrollTo({ top: 0, behavior: 'instant' }); el.dispatchEvent(new Event('scroll')); });
	await page.waitForFunction(() => document.querySelector('.wiki-toc button:first-of-type')?.getAttribute('aria-current') === 'location');
	await page.screenshot({ path: '/tmp/pi-wiki-reading-dark.png' });
	await page.evaluate(() => { document.documentElement.dataset.appearance = 'light'; localStorage.setItem('pi-web-ui:code-theme', 'light'); window.dispatchEvent(new Event('pi-web-ui:code-theme')); });
	await page.getByRole('button', { name: '展开提问框', exact: true }).click();
	await page.waitForFunction(() => {
		const code = document.querySelector('.wiki-prose .codeblock');
		return getComputedStyle(code).backgroundColor === getComputedStyle(code).backgroundColor;
	});
	await page.screenshot({ path: '/tmp/pi-wiki-reading-light-expanded.png' });
	await page.keyboard.press('Escape');
	await page.evaluate(() => { document.documentElement.dataset.appearance = 'dark'; });
	await page.keyboard.press('Meta+k');
	await page.locator('.wiki-search-modal input').fill('Hidden searchable');
	await page.locator('.wiki-search-results strong', { hasText: '.obsidian/hidden.md' }).click();
	await page.locator('.wiki-document-heading h1', { hasText: 'Different page title' }).waitFor();
	assert.equal(await page.locator('.wiki-prose h1').innerText(), 'Different body title');
	await page.locator('.wiki-tree-row[title="README.md"]').click();
	await page.locator('.wiki-document-heading h1', { hasText: '风控规则' }).waitFor();

	assert.equal(await page.locator('.wiki-prose a').first().textContent(), '参数配置');
	await page.locator('.wiki-prose a').first().click();
	await page.locator('.wiki-document h1:visible', { hasText: '参数配置' }).waitFor();
	// Re-enter from a different file after Wiki has already mounted: the click wins over cached/internal navigation.
	await page.getByRole('tab', { name: '对话', exact: true }).click();
	await page.locator('.file-name', { hasText: 'README.md' }).click();
	await page.locator('.wiki-document h1:visible', { hasText: '风控规则' }).waitFor();
	await page.getByRole('tab', { name: '对话', exact: true }).click();
	await page.locator('.file-dir-main', { hasText: 'risk' }).click();
	await page.locator('.file-name', { hasText: 'guard.py' }).click();
	await page.locator('.fp-editor').fill('unsaved code draft');
	await page.keyboard.press('Meta+k');
	await page.locator('.gs-input-row input').fill('参数配置.md');
	await page.locator('.gs-item', { hasText: '参数配置.md' }).click();
	await page.locator('.fp-leave').waitFor();
	await page.locator('.fp-leave').getByRole('button', { name: '取消', exact: true }).click();
	assert.equal(await page.locator('.fp-editor').inputValue(), 'unsaved code draft');
	await page.evaluate(() => window.dispatchEvent(new CustomEvent('pi-web-ui:open-tool-file', { detail: { path: '交易系统/参数配置.md' } })));
	await page.locator('.fp-leave').getByRole('button', { name: '放弃修改', exact: true }).click();
	await page.locator('.wiki-document h1:visible', { hasText: '参数配置' }).waitFor();
	assert.equal(readFileSync(join(cwd, 'risk', 'guard.py'), 'utf8'), 'def check_stop(loss):\n    return loss >= 0.02\n');
	assert.equal(await page.locator('.fp-editor').count(), 0, 'old preview unmounted on Markdown navigation');
	await page.locator('.wiki-backlinks > button').waitFor();
	assert.equal(await page.locator('.wiki-backlinks > button').count(), 1);
	await page.locator('.wiki-backlinks > button').click();
	await page.locator('.wiki-document h1:visible', { hasText: '风控规则' }).waitFor();
	await page.keyboard.press('Meta+k');
	await page.locator('.wiki-search-modal input').fill('阈值');
	await page.locator('.wiki-search-results strong', { hasText: '参数配置.md' }).waitFor();
	await page.keyboard.press('Escape');
	// Markdown is editable immediately in its rendered layout; both modes share the draft.
	const rendered = page.locator('.wiki-prose [contenteditable="true"][role="textbox"]');
	await rendered.waitFor();
	await rendered.locator('p').first().click({ position: { x: 10, y: 5 } });
	await page.keyboard.press('End');
	await page.keyboard.type(' Preview edit.');
	await page.locator('.wiki-save').waitFor();
	await page.getByRole('button', { name: '编辑源码', exact: true }).click();
	assert((await page.locator('.wiki-document textarea').inputValue()).includes('Preview edit.'));
	assert((await page.locator('.wiki-document textarea').inputValue()).startsWith('---\ntitle:'));
	await page.getByRole('button', { name: '渲染预览', exact: true }).click();
	assert((await rendered.innerText()).includes('Preview edit.'));
	const beforePreviewSave = readFileSync(join(cwd, 'README.md'), 'utf8');
	await page.getByRole('button', { name: '保存', exact: true }).click();
	await page.waitForFunction(() => !document.querySelector('.wiki-save'));
	const afterPreviewSave = readFileSync(join(cwd, 'README.md'), 'utf8');
	assert(afterPreviewSave.includes('Preview edit.'));
	assert.equal(afterPreviewSave.split('# 风控规则')[0], beforePreviewSave.split('# 风控规则')[0], 'frontmatter preserved');
	assert(afterPreviewSave.includes('[[参数配置]]'), 'Wiki syntax preserved inside an edited paragraph');
	assert(afterPreviewSave.includes('```js\nconst color = "#ff475040"; // #notatag\n```'), 'untouched code remains exact');
	await rendered.click();
	await page.keyboard.press('Meta+a');
	await page.keyboard.type('Replacement body.');

	await page.getByRole('button', { name: '编辑源码', exact: true }).click();
	assert((await page.locator('.wiki-document textarea').inputValue()).startsWith('---\ntitle:'), 'select-all retains hidden metadata');
	assert((await page.locator('.wiki-document textarea').inputValue()).includes('# 风控规则'), 'select-all retains hidden title');
	await page.locator('.wiki-document textarea').fill('# 风控规则\n\n手动修改。\n');
	await page.keyboard.press('Meta+n');
	await page.getByRole('dialog', { name: '有未保存修改' }).waitFor();
	await page.getByRole('button', { name: '取消', exact: true }).click();
	await page.getByRole('tab', { name: '对话', exact: true }).click();
	await page.getByRole('dialog', { name: '有未保存修改' }).waitFor();
	await page.getByRole('button', { name: '取消', exact: true }).click();
	await page.getByRole('button', { name: '保存', exact: true }).click();
	await page.waitForFunction(() => !document.querySelector('.wiki-save'));
	assert.equal(readFileSync(join(cwd, 'README.md'), 'utf8'), '# 风控规则\n\n手动修改。\n');
	await page.getByRole('button', { name: '最近改动', exact: true }).click();
	await page.locator('.wiki-file-change').first().waitFor();
	await page.getByRole('button', { name: '全部撤销', exact: true }).first().click();
	await page.waitForFunction(() => document.querySelector('.wiki-file-change')?.classList.contains('undone'));
	assert(readFileSync(join(cwd, 'README.md'), 'utf8').includes('仓位上限'));
	await page.locator('.wiki-changes header button').click();
	await page.getByRole('button', { name: '渲染预览', exact: true }).click();
	// Selection toolbar routes quoted content into the visible request.
	await page.locator('.wiki-prose p').first().evaluate(el => { const s = window.getSelection(), r = document.createRange(); r.selectNodeContents(el); s.removeAllRanges(); s.addRange(r); el.dispatchEvent(new MouseEvent('mouseup', { bubbles: true })); });
	await page.locator('.wiki-selection-menu').waitFor();
	await page.getByRole('button', { name: '解释', exact: true }).click();
	assert((await page.locator('.wiki-context-chips').innerText()).includes('选中内容'));
	await page.getByRole('textbox', { name: '问 pi', exact: true }).fill('请补充隔夜持仓规则并更新参数配置文档。');
	await page.getByRole('button', { name: '范围', exact: true }).click();
	await page.getByRole('button', { name: '范围 · 整个工作区', exact: true }).click();
	await page.getByRole('button', { name: '范围', exact: true }).click();
	await page.getByRole('button', { name: '查看发送内容', exact: true }).click();
	assert((await page.locator('.wiki-prompt-preview').innerText()).includes('代码文件默认只读'));
	await page.getByRole('button', { name: '范围', exact: true }).click();
	await page.getByRole('button', { name: '查看发送内容', exact: true }).click();
	await page.keyboard.press('Meta+j');
	assert.equal(await page.locator('.wiki-chat-panel').count(), 0);
	await page.getByRole('button', { name: '发送', exact: true }).click();
	await page.locator('.wiki-chat-panel .waiting-header-status .working-dots').waitFor();
	await page.locator('.wiki-chat-panel .thinking.live').waitFor();
	assert((await page.locator('.wiki-chat-panel .thinking.live').innerText()).includes('先核对文档'));
	await page.locator('.wiki-chat-answer', { hasText: '已更新两个文档' }).waitFor({ timeout: 20000 });
	await page.getByRole('button', { name: '跳到 §2', exact: true }).waitFor();
	await page.locator('.wiki-change-toast', { hasText: '2 个文件' }).waitFor({ timeout: 20000 });
	assert(requests.length >= 2);
	await page.getByRole('button', { name: '跳到 §2', exact: true }).waitFor();
	assert.equal(await page.getByRole('button', { name: '跳到 §99', exact: true }).count(), 0);
	await page.getByRole('button', { name: '跳到 §2', exact: true }).click();
	assert.equal(await page.locator('.wiki-save').count(), 0, 'heading flash does not dirty the editor');
	assert.equal(await page.locator('.wiki-chat-tool.done').count(), 2, 'tools show actual completion');
	assert((await page.locator('.wiki-chat-messages').innerText()).includes('需要我继续吗？'));
	await page.screenshot({ path: '/tmp/pi-wiki-chat-desktop.png' });
	await page.evaluate(() => document.documentElement.dataset.appearance = 'light');
	await page.screenshot({ path: '/tmp/pi-wiki-chat-desktop-light.png' });
	await page.evaluate(() => document.documentElement.dataset.appearance = 'dark');
	const previousConversation = activeConversation, previousSession = activeSnapshot.sessionId, previousFile = activeSnapshot.sessionFile;
	assert.equal(typeof previousConversation, "string");
	if (await page.locator('.wiki-tree-row[title="交易系统"]').getAttribute('aria-expanded') !== 'true') await page.locator('.wiki-tree-row[title="交易系统"]').click();
	await page.locator('.wiki-chat-panel').getByRole('button', { name: '收起对话面板', exact: true }).click();
	holdSnapshots = true;
	const newDocument = page.waitForResponse(response => response.url().endsWith('/api/wiki') && response.request().postDataJSON()?.action === 'new-conversation');
	await page.locator('.wiki-tree-row[title="交易系统/参数配置.md"]').click();
	assert.equal((await newDocument).status(), 200);
	await page.getByRole('textbox', { name: '问 pi', exact: true }).fill('must not send into the old conversation');
	assert(await page.getByRole('button', { name: '会话准备中', exact: true }).isDisabled(), 'wait for the new conversation snapshot before sending');
	releaseSnapshots();
	await page.locator('.wiki-document-heading h1', { hasText: '参数配置' }).waitFor();
	await page.locator('.wiki-chat-panel').waitFor();
	assert.notEqual(activeConversation, previousConversation, 'document switch creates a distinct native conversation');
	assert.notEqual(activeSnapshot.sessionId, previousSession, 'native SDK session identity is distinct');
	assert(!previousFile && !activeSnapshot.sessionFile, 'Wiki conversations never create native history files');
	assert(!(await page.locator('.wiki-chat-messages').innerText()).includes('已更新两个文档'), 'document switches start a fresh conversation');
	assert((await page.locator('.wiki-context-chips').innerText()).includes('参数配置.md'));
	await page.getByRole('textbox', { name: '问 pi', exact: true }).fill('仅确认当前文档');
	await page.getByRole('button', { name: '发送', exact: true }).click();
	await page.locator('.wiki-chat-answer', { hasText: '当前文档已确认' }).waitFor();
	assert.equal(requests.at(-1).messages.filter(m => m.role === 'user').length, 1, 'provider receives only the new document conversation');
	assert(!JSON.stringify(requests.at(-1).messages).includes('请补充隔夜持仓规则'), 'previous document context is absent from provider request');

	await page.locator('.wiki-tree-row[title="README.md"]').click();
	await page.locator('.wiki-document-heading h1', { hasText: '风控规则' }).waitFor();
	assert(requests.some(r => r.messages.some(m => m.role === 'tool')), 'native SDK executed tool calls');
	assert(JSON.stringify(requests[0].messages).includes('选中内容'));
	await page.locator('.wiki-change-toast button').first().click();
	await page.locator('.wiki-file-change').first().waitFor();
	assert(await page.getByRole('button', { name: '展开提问框', exact: true }).isVisible(), 'sending collapses the composer');
	const main = await page.locator('.wiki-composer-area').boundingBox(), drawer = await page.locator('.wiki-changes').boundingBox();
	assert(main.x + main.width <= drawer.x, 'composer overlaps drawer');
	mkdirSync('tests/scratch', { recursive: true });
	await page.screenshot({ path: 'tests/scratch/wiki-desktop.png' });
	await page.getByRole('button', { name: '全部撤销', exact: true }).click();
	await page.waitForFunction(() => [...document.querySelectorAll('.wiki-file-change')].every(el => el.classList.contains('undone')));
	assert(!readFileSync(join(cwd, 'README.md'), 'utf8').includes('隔夜持仓'));
	await page.getByRole('button', { name: '全部重做', exact: true }).click();
	await page.waitForFunction(() => [...document.querySelectorAll('.wiki-file-change')].every(el => !el.classList.contains('undone')));
	assert(readFileSync(join(cwd, 'README.md'), 'utf8').includes('隔夜持仓'));
	await page.locator('.wiki-changes header button').click();
	await page.setViewportSize({ width: 390, height: 844 });
	assert(!(await page.locator('.wiki-toc').isVisible()));
	const closedWidth = (await page.locator('.wiki-main').boundingBox()).width;
	await page.locator('.wiki-chat-toggle').click();
	await page.getByRole('dialog', { name: 'Wiki 对话面板', exact: true }).waitFor();
	assert.equal((await page.locator('.wiki-main').boundingBox()).width, closedWidth, 'mobile chat overlays instead of squeezing article');
	assert(await page.getByRole('textbox', { name: '问 pi', exact: true }).isVisible());
	await page.screenshot({ path: '/tmp/pi-wiki-chat-mobile.png' });
	await page.locator('.wiki-chat-panel').getByRole('button', { name: '收起对话面板', exact: true }).click();
	await page.locator('.wiki-scroll').evaluate(el => el.scrollTop = el.scrollHeight);
	const end = await page.locator('.wiki-backlinks').boundingBox(), composer = await page.locator('.wiki-composer-area').boundingBox();
	assert(end.y + end.height <= composer.y, 'last content can scroll above the floating composer');
	await page.screenshot({ path: 'tests/scratch/wiki-mobile.png' });
	assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile overflow');
	await page.locator('.wiki-mobile-tools button').first().click();
	await page.locator('.wiki-sidebar.open').waitFor();
	await page.keyboard.press('Escape');
	await page.setViewportSize({ width: 1440, height: 1000 });
	await page.locator('.wiki-chat-toggle').click();
	await page.locator('.wiki-chat-panel').getByRole('button', { name: '新对话', exact: true }).click();
	await page.locator('.wiki-chat-empty').waitFor();
	await page.locator('.wiki-document-heading h1', { hasText: '风控规则' }).waitFor();
	assert.equal(await page.locator('.wiki-chat-answer').count(), 0, 'new native conversation clears the panel');
	assert(wikiConversations.length > 8, 'can browse more documents than the runtime limit');
	assert.equal(new Set(wikiConversations).size, wikiConversations.length, 'each document navigation receives a fresh native conversation');
	assert.deepEqual(errors, []);
	console.log('PASS Wiki layout, links, search, source save, draft guard, selection, native request, batch undo/redo and mobile');
} catch (e) { const page = browser?.contexts()[0]?.pages()[0]; if (page) { await page.screenshot({ path: '/tmp/pi-wiki-regression-failure.png' }); console.error(await page.locator('.wiki-document-heading').innerText().catch(() => 'No document')); } console.error(log.slice(-5000)); throw e; }
finally { await browser?.close(); server.kill('SIGTERM'); await new Promise(r => server.once('exit', r)); await new Promise(r => mock.close(r)); rmSync(base, { recursive: true, force: true }); }
